package mum.ea.movie.domain;

public enum Genre {
	
	ACTION, ANIMATION
	, COMEDY, DOCUMENTARY
	, FAMILY, FILM_NOIR
	, HORROR, MUSICAL
	, ROMANCE, SPORT
	, WAR, ADVENTURE
	, BIOGRAPHY, CRIME
	, DRAMA, FANTASY
	, HISTORY, MUSIC
	, MYSTERY, SCI_FI
	, THRILLER, WESTERN

	
}
